// Activity Reference Lists — ported unchanged from virtual-career-counselling (display only, never stored)

export const ACTIVITY_REFERENCE_LISTS = {
    preHighSchool: [
        "Cricket (playing, coaching, or watching)",
        "Football/Soccer (playing, team sports)",
        "Swimming (learning, practicing, competitions)",
        "Running (track events, marathons, daily jogging)",
        "Cycling (bike riding, cycling competitions)",
        "Drawing (sketching, painting, art classes)",
        "Painting (watercolors, oil painting, canvas work)",
        "Music (singing, learning instruments, school choir)",
        "Dance (classical, folk, school performances)",
        "Reading (books, comics, magazines, newspapers)",
        "Writing (stories, diary, poems, school essays)",
        "Mathematics (solving problems, competitions, olympiads)",
        "Science (experiments, projects, science fairs)",
        "Computer programming (basic coding, educational software)",
        "Chess (playing, tournaments, learning strategies)",
        "Board games (carrom, ludo, monopoly, scrabble)",
        "Puzzles (jigsaw, crosswords, brain teasers)",
        "Collecting (stamps, coins, cards, shells, rocks)",
        "Gardening (planting, caring for plants, school garden)",
        "Cooking (helping in kitchen, simple recipes, baking)",
        "Photography (taking photos, learning camera skills)",
        "Storytelling (telling stories, listening to family histories)",
        "Leadership (class monitor, team captain, group leader)",
        "Volunteering (helping teachers, community service)",
        "Teaching others (helping siblings, explaining to friends)",
        "Public speaking (school assemblies, presentations)",
        "Nature exploration (hiking, camping, bird watching)",
        "Building things (LEGO, model kits, cardboard crafts)",
        "Language learning (English, mother tongue, other languages)",
        "Religious activities (prayers, festivals, community service)",
        "Cultural activities (traditional celebrations, community events)",
        "Family activities (trips, household chores, family time)",
        "Social activities (birthday parties, sleepovers, friendships)",
        "Other (please specify any activity not listed)",
    ],
    highSchool: [
        "Mathematics (advanced problem solving, competitions, olympiads)",
        "Physics (experiments, projects, science competitions)",
        "Chemistry (lab work, research projects, science fairs)",
        "Biology (dissections, field studies, research)",
        "Computer Science (programming, coding competitions, projects)",
        "English Literature (creative writing, poetry, debates)",
        "History (research, projects, essay competitions)",
        "Basketball (playing, team captain, tournaments)",
        "Football (playing, team sports, competitions)",
        "Tennis (playing, coaching, tournaments)",
        "Swimming (competitive swimming, coaching)",
        "Cricket (playing, team captain, tournaments)",
        "Drawing (sketching, art classes, exhibitions)",
        "Painting (canvas work, art competitions, exhibitions)",
        "Photography (photo projects, competitions, exhibitions)",
        "Digital Art (graphic design, digital painting, projects)",
        "Music (choir, band, orchestra, instrument learning)",
        "Theater (school plays, drama club, acting)",
        "Dance (classical, contemporary, choreography)",
        "Creative Writing (poetry, stories, school magazine)",
        "Journalism (school newspaper, reporting, editing)",
        "Debate (formal debates, Model UN, competitions)",
        "Public Speaking (speeches, oratory competitions)",
        "Student Council (class representative, president)",
        "Leadership (club president, team captain, organizer)",
        "Academic Competitions (olympiads, quiz competitions)",
        "Social Activism (awareness campaigns, fundraising)",
        "Volunteering (tutoring, community service, hospital work)",
        "Programming (coding clubs, app development, robotics)",
        "Research (science projects, independent studies)",
        "Internships (job shadowing, career exploration)",
        "Yearbook (editing, photography, design)",
        "School Newspaper (writing, editing, publishing)",
        "Science Club (experiments, projects, competitions)",
        "Language Club (foreign languages, cultural activities)",
        "Environmental Club (conservation, sustainability projects)",
        "Religious Activities (youth group, service projects)",
        "Cultural Activities (festivals, cultural clubs)",
        "Chess (playing, tournaments, strategy)",
        "Video Games (competitive gaming, e-sports)",
        "Blogging (content creation, digital communication)",
        "Environmental Projects (conservation, sustainability)",
        "Entrepreneurship (school store, selling crafts)",
        "Tutoring (peer tutoring, teaching younger students)",
        "Personal Projects (collections, crafts, DIY)",
        "Family Responsibilities (caring for siblings, household)",
        "Reading (fiction, non-fiction, newspapers)",
        "Yoga (practice, teaching, competitions)",
        "Meditation (practice, workshops, retreats)",
        "Gym (fitness training, bodybuilding)",
        "Travel (school trips, family travels, exchange programs)",
        "Cooking (learning recipes, meal preparation)",
        "Baking (pastry making, cake decorating)",
        "Social Events (organizing gatherings, school events)",
        "Other (please specify any activity not listed)",
    ],
    college: [
        "Research (lab work, field studies, thesis, dissertation)",
        "Internships (summer internships, semester placements, industry projects)",
        "Part-time Jobs (teaching assistantships, campus jobs, retail)",
        "Leadership (club president, team captain, class representative)",
        "Student Council (elections, organizing events, representation)",
        "Cultural Clubs (organizing festivals, performances, events)",
        "Academic Associations (conferences, workshops, networking)",
        "Volunteering (community service, mentoring, tutoring)",
        "NGO Work (field work, awareness campaigns, fundraising)",
        "Startups (founding companies, business competitions)",
        "Freelance Work (consulting, design, development)",
        "Coding Projects (web development, mobile apps, software)",
        "Engineering Projects (design competitions, prototypes)",
        "Case Competitions (business cases, strategy competitions)",
        "Certifications (technical, professional, language)",
        "Workshops (skill development, industry training)",
        "Conferences (attending, presenting, organizing)",
        "Music (college band, orchestra, solo performances)",
        "Theater (college plays, drama club, acting)",
        "Dance (college performances, choreography, competitions)",
        "Painting (art exhibitions, commissions, projects)",
        "Photography (photo projects, exhibitions, freelance)",
        "College Newspaper (writing, editing, publishing)",
        "Blogging (personal blogs, technical writing, reviews)",
        "Creative Writing (poetry, stories, publications)",
        "Research Papers (academic writing, publications)",
        "Varsity Sports (college teams, tournaments, coaching)",
        "Intramural Sports (recreational leagues, tournaments)",
        "Fitness (gym, yoga, running, cycling)",
        "Festivals (organizing, participating, cultural events)",
        "International Student Groups (cultural exchange, events)",
        "Language Clubs (foreign languages, conversation groups)",
        "Religious Groups (prayer groups, service activities)",
        "Student Politics (elections, campaigns, activism)",
        "Activism (awareness campaigns, protests, advocacy)",
        "Technical Skills (programming, design software, lab techniques)",
        "Video Creation (YouTube, educational content, vlogs)",
        "Podcasting (recording, editing, publishing)",
        "Social Media (content creation, digital marketing)",
        "Website Development (personal sites, client projects)",
        "Study Abroad (exchange programs, international courses)",
        "Educational Trips (field visits, industry tours)",
        "Peer Tutoring (helping classmates, study groups)",
        "TA Positions (teaching assistantships, grading)",
        "Mentoring (guiding juniors, career advice)",
        "Debates (college debates, Model UN, competitions)",
        "Presentations (academic, business, public speaking)",
        "TED-style Talks (public speaking, idea sharing)",
        "Career Fairs (attending, organizing, networking)",
        "Professional Mixers (alumni events, industry networking)",
        "Alumni Events (networking, mentoring, organizing)",
        "Research Publications (papers, journals, conferences)",
        "Creative Publications (magazines, anthologies, zines)",
        "Digital Content (websites, apps, online platforms)",
        "Investment Clubs (stock market, financial planning)",
        "Personal Finance (budgeting, investing, scholarships)",
        "Gaming (competitive gaming, e-sports, tournaments)",
        "Cooking (meal preparation, culinary experiments)",
        "Photography (photo projects, exhibitions, freelance)",
        "Collecting (hobbies, interests, specialized collections)",
        "Dating (relationships, social networking)",
        "Friendship Building (social groups, activities)",
        "Professional Networking (LinkedIn, industry connections)",
        "Yoga (practice, teaching, workshops)",
        "Meditation (practice, retreats, mindfulness)",
        "Fitness Routines (workout plans, training programs)",
        "Other (please specify any activity not listed)",
    ],
    postCollege: [
        "Career Promotions (advancement, role changes, industry transitions)",
        "Job Changes (switching companies, industries, roles)",
        "Industry Transitions (changing fields, new sectors)",
        "MBA (business school, executive education)",
        "CPA (accounting certification, professional development)",
        "PMP (project management certification)",
        "Technical Certifications (AWS, Azure, Cisco, etc.)",
        "Masters Degree (specialized programs, research)",
        "PhD (doctoral research, academic pursuits)",
        "Specialized Programs (executive education, diplomas)",
        "Team Leadership (managing teams, project leadership)",
        "Project Management (leading projects, methodologies)",
        "Executive Positions (senior management, C-level roles)",
        "Technical Expertise (specialized skills, subject matter expertise)",
        "Industry Conferences (attending, presenting, organizing)",
        "Professional Associations (membership, leadership roles)",
        "Alumni Groups (networking, mentoring, organizing)",
        "Mentoring (new employees, interns, junior colleagues)",
        "Startups (founding companies, co-founding, early stage)",
        "Side Businesses (consulting, freelancing, small ventures)",
        "Consulting (independent consulting, advisory work)",
        "Board Positions (non-profit boards, advisory boards)",
        "Committee Leadership (organizational committees, community groups)",
        "Volunteer Coordination (managing volunteers, community service)",
        "Parenting (raising children, family management)",
        "Elder Care (caring for parents, family members)",
        "Household Management (home organization, family logistics)",
        "Fitness Routines (gym, running, cycling, sports)",
        "Mental Health Practices (therapy, meditation, wellness)",
        "Nutrition (diet planning, meal preparation, health)",
        "Investment Planning (stocks, mutual funds, retirement)",
        "Retirement Planning (401k, IRA, financial planning)",
        "Budgeting (personal finance, expense tracking)",
        "Home Ownership (buying property, renovations, decoration)",
        "Property Renovations (home improvement, DIY projects)",
        "International Travel (business trips, vacations, sabbaticals)",
        "Work Travel (business trips, conferences, client visits)",
        "Sabbaticals (career breaks, extended travel, learning)",
        "Writing (books, articles, blogs, technical writing)",
        "Art (painting, sculpture, digital art, exhibitions)",
        "Music (playing instruments, composing, performances)",
        "Crafts (DIY projects, handmade items, creative work)",
        "Nonprofit Work (volunteering, board positions, fundraising)",
        "Community Service (local organizations, charity work)",
        "Pro Bono Work (professional services, legal, consulting)",
        "Workshops (teaching, conducting, organizing)",
        "Guest Lectures (academic, industry, community)",
        "Coaching (executive coaching, life coaching, mentoring)",
        "Conference Speaking (presentations, keynotes, panels)",
        "Event Speaking (corporate events, community events)",
        "Panel Discussions (moderating, participating, organizing)",
        "Book Writing (authoring, publishing, marketing)",
        "Article Writing (magazines, journals, online publications)",
        "Blog Writing (personal blogs, professional content)",
        "Research Papers (academic, industry, technical)",
        "Podcast Creation (recording, editing, publishing)",
        "Video Creation (YouTube, educational content, marketing)",
        "Website Development (personal sites, client projects)",
        "Social Media (content creation, digital marketing)",
        "Adult Sports Leagues (basketball, soccer, tennis)",
        "Outdoor Activities (hiking, camping, adventure sports)",
        "Fitness (gym, yoga, personal training)",
        "Collecting (hobbies, interests, specialized collections)",
        "Gaming (video games, board games, competitive gaming)",
        "Gardening (plant care, landscaping, urban farming)",
        "Cooking (meal preparation, culinary experiments)",
        "Theater (attending, performing, supporting)",
        "Concerts (attending, performing, organizing)",
        "Exhibitions (art, museums, cultural events)",
        "Festivals (attending, organizing, participating)",
        "Religious Practice (prayer, meditation, community involvement)",
        "Spiritual Practice (meditation, mindfulness, retreats)",
        "Political Campaigns (volunteering, organizing, running)",
        "Advocacy (policy work, awareness campaigns, lobbying)",
        "Local Politics (community involvement, local government)",
        "Networking (professional events, social groups, clubs)",
        "Community Groups (local organizations, social clubs)",
        "Online Courses (MOOCs, skill development, certifications)",
        "Workshops (attending, organizing, teaching)",
        "Reading (books, articles, research, professional development)",
        "Medical Care (health management, preventative care)",
        "Other (please specify any activity not listed)",
    ],
}
