// Problem prompts — click-to-add examples that help students RECALL problems (recognition is easier than recall).
//
// DRAFT FOR REVIEW. A prompt list is a leading instrument: whatever is listed here gets reported more often.
// Keep the three problem types balanced in count and intensity for each stage — an unbalanced list skews
// which problems students report, and that flows into drivingReasons matching on Day 3.
// Every problem a student adds from here is saved with source: "prompt".
//
// 4 life stages × 3 problem types × 11 prompts

export const PROBLEM_PROMPTS = {
    preHighSchool: {
        individualInternalProblems: [
            "Scared to speak or answer in front of the class",
            "Felt I wasn't as smart as other kids",
            "Got very nervous before exams or tests",
            "Struggled to understand a subject like maths or English",
            "Too shy to make new friends",
            "Gave up easily when something felt hard",
            "Worried a lot about making mistakes",
            "Had trouble concentrating in class",
            "Felt embarrassed about how I looked or spoke",
            "Afraid of trying new things like sports or stage events",
            "Found it hard to handle losing a game or competition",
        ],
        interpersonalInternalProblems: [
            "Got teased or bullied by other children",
            "Felt left out of a friend group",
            "Compared with siblings or cousins by family",
            "Arguments or tension at home",
            "Pressure from parents to score high marks",
            "Fell out with a close friend",
            "A teacher who was harsh or unfair to me",
            "Moved schools or cities and lost friends",
            "Felt my parents didn't have time for me",
            "Pushed into an activity I didn't enjoy",
            "Hard to fit in because of my language or background",
        ],
        externalProblems: [
            "Not enough money at home for books, tuition or classes",
            "My school had poor teachers or facilities",
            "No playground or sports facilities nearby",
            "Long or unsafe travel to school",
            "Frequent power cuts or no quiet place to study",
            "Garbage, pollution or dirty surroundings in my area",
            "Illness or health problems in the family",
            "Changed schools often because of a parent's job",
            "No internet or computer at home",
            "Treated differently because of gender, caste or community",
            "A flood, disaster or crisis that disrupted school",
        ],
    },
    highSchool: {
        individualInternalProblems: [
            "Exam stress and fear of board exams",
            "Confused about which stream or career to choose",
            "Low confidence in my abilities",
            "Procrastinating and struggling to manage time",
            "Fear of public speaking or presentations",
            "Losing motivation to study",
            "Anxious about my future",
            "Found a subject very difficult (e.g., maths, science)",
            "Too hard on myself, a perfectionist",
            "Distracted by phone, social media or games",
            "Felt I wasn't good at anything in particular",
        ],
        interpersonalInternalProblems: [
            "Parents pushing a stream or career I didn't want",
            "Constant comparison with toppers, siblings or cousins",
            "Peer pressure to skip classes or follow the crowd",
            "Conflicts with close friends",
            "Felt lonely or didn't fit in at school",
            "Bullied or made fun of",
            "Teachers who didn't support or understand me",
            "Fights or tension at home",
            "Pressure to join coaching (e.g., JEE/NEET) I didn't want",
            "Couldn't talk openly with my parents about my interests",
            "Friendship or relationship drama affecting my studies",
        ],
        externalProblems: [
            "Couldn't afford coaching, tuition or study material",
            "Few good schools or colleges nearby",
            "No one to guide me about career options",
            "Long commute or no safe transport",
            "Studied in a language I wasn't comfortable with",
            "No internet, laptop or quiet place to study",
            "Family money problems or a parent losing a job",
            "Health problems (mine or my family's)",
            "Gender expectations limited what I could do",
            "Pollution, water or waste problems in my community",
            "Disruption like COVID or moving cities",
        ],
    },
    college: {
        individualInternalProblems: [
            "Unsure whether I chose the right course",
            "Fear of networking or approaching seniors and professors",
            "Low confidence in interviews or group discussions",
            "Struggled to balance studies and other activities",
            "Lost interest in my subjects",
            "Anxiety about placements and jobs",
            "Felt everyone else was better than me",
            "Procrastinating before deadlines and exams",
            "Didn't know which skills to build",
            "Fear of failing or getting backlogs",
            "Hard to adjust to living independently",
        ],
        interpersonalInternalProblems: [
            "Conflicts in group projects",
            "Homesick or left out after moving for college",
            "Family pressure about marks, placements or career",
            "Comparing myself with friends' internships and offers",
            "Ragging or bullying",
            "Hard to work with a professor or mentor",
            "Friendship or relationship problems",
            "Pressure to do what my friends were doing",
            "Language or cultural differences with classmates",
            "Parents not supporting a new interest or career change",
            "Couldn't find like-minded people",
        ],
        externalProblems: [
            "High fees or education loan pressure",
            "Outdated curriculum not linked to real jobs",
            "Few internship or placement opportunities",
            "Poor college infrastructure or labs",
            "Campus sustainability or cleanliness issues",
            "Long commute or expensive living costs",
            "No career guidance on campus",
            "Had to work part-time to support myself",
            "Poor access to internet or a laptop",
            "Discrimination on campus (gender, caste, region)",
            "Exams or semesters disrupted (strikes, COVID)",
        ],
    },
    postCollege: {
        individualInternalProblems: [
            "Career uncertainty — unsure what I really want",
            "Low confidence in my skills at work",
            "Fear of switching careers",
            "Burnout or low motivation",
            "Struggled with time management and productivity",
            "Fear of speaking up in meetings",
            "Felt stuck and not growing",
            "Worried about job security or AI replacing my work",
            "Kept postponing learning new skills",
            "Felt like I didn't deserve my role",
            "Hard to set long-term goals",
        ],
        interpersonalInternalProblems: [
            "Conflicts with a manager or colleagues",
            "Work-life balance straining family relationships",
            "Family pressure to settle down or take a 'safe' job",
            "Comparing my salary and promotions with peers",
            "Office politics",
            "No mentor or senior to guide me",
            "Felt isolated working remotely or in a new city",
            "Difficulty managing or leading a team",
            "My work wasn't recognised",
            "Disagreements with family about my career choices",
            "Losing touch with friends",
        ],
        externalProblems: [
            "Financial constraints or loan repayments",
            "Few jobs in my field or city",
            "Layoffs or my company shutting down",
            "Low salary compared to living costs",
            "Long commute or high rent",
            "My industry changing fast (automation, AI)",
            "Health problems (mine or my family's)",
            "Needed to support my family financially",
            "No affordable courses to upskill",
            "Discrimination at work (gender, age, background)",
            "Economic slowdown or hiring freeze",
        ],
    },
}
